<div class="row">
    <div class="col-md-3">
        <ul>
            <li>
                <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'index')); ?>">Мої внески</a>
            </li>
            <li>
                <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'create-donation')); ?>">Створити внесок</a>
            </li>
            <li>
                <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'my-data')); ?>">Мої дані</a>
            </li>
        </ul>
    </div>
    <div class="col-md-9">
        <?php
        $form->setAttribute('action', $this->url('site/donor-page', array('action' => 'create-donation')));
        $form->prepare();

        echo $this->form()->openTag($form);

        echo $this->formRow($form->get('name'));
        echo $this->formRow($form->get('image'));
        echo $this->formRow($form->get('full_description'));
        echo $this->formRow($form->get('categories_main_id'));
        echo $this->formRow($form->get('categories_sub_id'));
        echo $this->formSubmit($form->get('submit'));

        echo $this->form()->closeTag();
        echo $message;
        ?>
    </div>
</div>
