<div class="row">
    <div class="col-md-3">
        <ul>
            <li>
                <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'index')); ?>">Мої внески</a>
            </li>
            <li>
                <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'create-donation')); ?>">Створити внесок</a>
            </li>
            <li>
                <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'my-data')); ?>">Мої дані</a>
            </li>
        </ul>
    </div>
    <div class="col-md-9">

    </div>
</div>
