<div class="row">
    <div class="col-md-3">
        <ul>
            <li>
                <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'index')); ?>">Мої внески</a>
            </li>
            <li>
                <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'create-donation')); ?>">Створити внесок</a>
            </li>
            <li>
                <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'my-data')); ?>">Мої дані</a>
            </li>
        </ul>
    </div>
    <div class="col-md-9">
        <?php
        if ($donor = $this->identity()) {
            echo "<br>Logged in as " . $this->escapeHtml($donor->getMail());
        }
        ?>
        <table class="table">
            <tr>
                <th>Дата</th>
                <th>Лінк</th>
                <th>Керування</th>
            </tr>
            <?php foreach($incomes as $income): ?>
                <tr>
                    <td><?php echo $income['date']; ?></td>
                    <td><?php echo $income['name']; ?></td>
                    <td>
                        <?php
                        if($income['visible']==0) {
                            echo 'Приховано';
                        }
                        else { ?>
                        <a href="<?php echo $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'hide-donation','id' => $income['id'])); ?>">Не відображати</a>
                        <?php
                        }
                        ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>
</div>
