<div class="row">
    <div class="col-md-3" style="background-color: orange">
        <ul>
            <li>
                <a href="<?php $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'index')); ?>">Мої внески</a>
            </li>
            <li>
                <a href="<?php $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'createDonation')); ?>">Створити внесок</a>
            </li>
            <li>
                <a href="<?php $this->url('site/donor-page',array('controller' => 'DonorPage','action' => 'myData')); ?>">Мої дані</a>
            </li>
        </ul>
    </div>
    <div class="col-md-9" style="background-color: yellow">

    </div>
</div>