<html lang="en">
<head>
    <?php
    $title = 'Додавання внеску';
    ?>
    <h1><center><?php echo $this->escapeHtml($title); ?></center></h1>
    <br>
</head>
<body>
<fieldset>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <p class="lead">Меню</p>
                <div class="list-group">
                    <a href="<?php echo $this->url('site/volunteers',array('controller' => 'AddDonation','action' => 'index')); ?>" class="list-group-item active">Каталог</a>
                    <a href="<?php echo $this->url('site/volunteers',array('controller' => 'AddDonation','action' => 'volunteers')); ?>" class="list-group-item">Додати внесок</a>

                </div>
            </div>


            <div class="col-lg-9">
                <table border="1">

                    <?php

                    echo "<tr>";
                    foreach ($users as $user){




                        echo "<td><h1>".$user['name']."</h1></td>";


                    }
                    echo "<tr>";


                    ?>
                    <table>
                </div>

                
        </div>
    </div>
</fieldset>

</body>

</html>
