

<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title">Додати категорію</h1>
        </div>
        <div class="panel-body">
            <?php
            $form->setAttribute('action', $this->url('site/admin', array('action' => 'add-categories-main')));
            $form->prepare();
            ?>
            <div class="col-lg-8">
                <?php echo $this->form()->openTag($form); ?>
                <fieldset>

                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('name'));
                        ?>
                        <div class="col-lg-8">
                            <?php   echo $this->formElement($form->get('name'));
                            echo $this->formElementErrors($form->get('name'));?>
                        </div>
                    </div>

                        <div class="form-group">
                            <div class="col-lg-8 col-lg-offset-4">
                                <?php echo $this->formSubmit($form->get('submit'));?>
                            </div>
                        </div>
                </fieldset>
                <?php echo $this->form()->closeTag();?>

            </div>
        </div>
    </div>
</div>