<?php


$title = 'Login and Search';
$this->headTitle($title);
?>
    <h1><center><?php echo $this->escapeHtml($title); ?></center></h1>
<?php
$formDonors->setAttribute('action', $this->url('site/home', array('action' => 'index')));
$formDonors->prepare();

echo $this->form()->openTag($formDonors);


echo $this->formRow($formDonors->get('mail'));
echo $this->formRow($formDonors->get('password'));
echo $this->formSubmit($formDonors->get('submit'));

echo $this->form()->closeTag();
?>




<?php
$formVolunteers->setAttribute('action', $this->url('site/home', array('action' => 'index')));
$formVolunteers->prepare();

echo $this->form()->openTag($formDonors);


echo $this->formRow($formVolunteers->get('login'));
echo $this->formRow($formVolunteers->get('password'));
echo $this->formSubmit($formVolunteers->get('submit'));

echo $this->form()->closeTag();
?>



<?php
$formSearch->setAttribute('action', $this->url('site/home', array('action' => 'search')));
$formSearch->prepare();

echo $this->form()->openTag($formSearch);


echo $this->formRow($formSearch->get('name'));
echo $this->formRow($formSearch->get('tracking_code'));
echo $this->formSubmit($formSearch->get('submit'));

echo $this->form()->closeTag();
?>