<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 12.05.2015
 * Time: 21:03
 */

$form->setAttribute('action', $this->url('site/home', array('action' => 'search')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('tracking_code'));
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
?>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Tracking Code</th>


        <th>&nbsp;</th>
    </tr>

    <?php   foreach($incomes_materials as $income_material) : ?>

        <tr>
            <td><?php echo $income_material['name'];?></td>
            <td><?php echo $income_material['tracking_code'];?></td>
        </tr>
    <?php endforeach; ?>
</table>