<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 14.05.2015
 * Time: 22:12
 */
//var_dump($this->users);
//echo $this->users->getCategoriesMainId();

die(print_r($users[0]['name']));s
?>
<table>
	<tr>
		<th>getUsrName</th>
		<th>getUsrPassword</th>
		<th>getUsrEmail</th>
		<th>getUsrlId</th>
		<th>getLngId</th>
	</tr>
<?php foreach ($users as $user) { ?>
    <tr>
        <td><?php echo $this->escapeHtml($user['name']);?></td>
        <td><?php echo $this->escapeHtml($user['date']);?></td>
    </tr>
<?php } ?>
</table>